---
- name: Configure smtpd
  lineinfile:
    path: "{{ postfix_config_path }}"
    regexp: '^(?P<name>#?{{ item.name }})(?P<operator>\\s*=\\s*)'
    line: "\\g<name>\\g<operator>{{ item.value }}"
    state: present
    create: yes
  when: item.value | length > 0
  loop: 
  - smtpd_use_tls: "{{ postfix_smtpd_use_tls | default('no') | ternary('yes', 'no') }}"
  - smtpd_tls_cert_file: "{{ postfix_smtpd_tls_cert_file | default('') }}"
  - smtpd_tls_key_file: "{{ postfix_smtpd_tls_key_file | default('') }}"
  - smtpd_tls_security_level: "{{ postfix_smtpd_tls_security_level | default('') }}"
  - smtpd_tls_loglevel: "{{ postfix_smtpd_tls_loglevel | default('') }}"
  - smtpd_sasl_auth_enable: "{{ postfix_smtpd_sasl_auth_enable | default('no') | ternary('yes', 'no') }}"
  - smtpd_sasl_type: "{{ postfix_smtpd_sasl_type | default('') }}"
  - smtpd_sasl_security_options: "{{ postfix_smtpd_sasl_security_options | default('') }}"
  - smtpd_recipient_restrictions: "{{ postfix_smtpd_recipient_restrictions | default([]) | join(', ') }}"
  - smtpd_relay_restrictions: "{{ postfix_smtpd_relay_restrictions | default([]) | join(', ') }}"
  notify: restart postfix
