---
- name: Configure smtp
  lineinfile:
    path: "{{ postfix_config_path }}"
    regexp: '^(?P<name>#?{{ item.name }})(?P<operator>\\s*=\\s*)'
    line: "\\g<name>\\g<operator>{{ item.value }}"
    state: present
    create: yes
  when: item.value | length > 0
  loop:
  - smtp_use_tls: "{{ postfix_smtp_use_tls | default('no') | ternary('yes', 'no') }}"
  - smtp_tls_security_level: "{{ postfix_smtp_tls_security_level | default('') }}"
  - smtp_tls_note_starttls_offer: "{{ postfix_smtp_tls_note_starttls_offer | default('no') | ternary('yes', 'no') }}"
  - smtp_sasl_auth_enable: "{{ postfix_smtp_sasl_auth_enable | default('no') | ternary('yes', 'no') }}"
  - smtp_sasl_type: "{{ postfix_smtp_sasl_type | default('') }}"
  - smtp_sasl_password_maps: "{{ postfix_smtp_sasl_password_maps | default('') }}"
  - smtp_sasl_security_options: "{{ postfix_smtp_sasl_security_options | default('') }}"
  notify: restart postfix
